before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_arm64
      - linux_arm_6
    ldflags:
      - -s -w -X mtauth/app.Version={{.Version}}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
- image_templates:
    - "buckaroobanzay/mtauth:{{ .Version }}"
    - "buckaroobanzay/mtauth:latest"
  dockerfile: Dockerfile