version: "3.6"

services:
 postgres:
  image: postgres:14.11
  restart: always
  ports:
   - "5432:5432"
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "postgres:/var/lib/postgresql/data"

 minetest:
  image: buckaroobanzay/minetest:5.5.0-r1
  restart: always
  ports:
   - "30000:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "minetest_data:/data"
   - "minetest_home:/root/.minetest"
   - "./test_world/minetest.conf:/data/minetest.conf"
   - "./test_world/world.mt:/data/world/world.mt"
  logging:
   options:
    max-size: 50m

volumes:
  postgres: {}
  minetest_data: {}
  minetest_home: {}